export {calculate}  from './calculate/calculate'
export {setState}   from './setState/setState'
export {isDecimal}  from './isDecimal/isDecimal'
export {setDecimal} from './setDecimal/setDecimal'
export {useOperand} from './useOperand/useOperand'
export {setNumber}  from './setNumber/setNumber'