export {clear}     from './basic/clear/clear'
export {decimal}   from './basic/decimal/decimal'
export {equals}    from './basic/equals/equals'
export {negation}  from './basic/negation/negation'
export {number}    from './basic/number/number'
export {operation} from './basic/operation/operation'
export {percent}   from './basic/percent/percent'
