export {equals}     from './basic/equals/equals'
export {clear}      from './basic/clear/clear'
export {decimal}    from './basic/decimal/decimal'
export {number}     from './basic/number/number'
export {operation}  from './basic/operation/operation'
export {percent}    from './basic/percent/percent'
export {toggleSign} from './basic/toggleSign/toggleSign'